import TataouineImage1 from "../src/assets/Tataouine_Images/caption (1).jpg"
import TataouineImage2 from "../src/assets/Tataouine_Images/caption (2).jpg"
import TataouineImage3 from "../src/assets/Tataouine_Images/caption (3).jpg"
import TataouineImage4 from "../src/assets/Tataouine_Images/caption (4).jpg"
import TataouineImage5 from "../src/assets/Tataouine_Images/caption (5).jpg"
import TataouineImage6 from "../src/assets/Tataouine_Images/caption (6).jpg"
import TataouineImage7 from "../src/assets/Tataouine_Images/caption (7).jpg"
import TataouineImage8 from "../src/assets/Tataouine_Images/caption (8).jpg"
import TataouineImage9 from "../src/assets/Tataouine_Images/caption (9).jpg"
import TataouineImage10 from "../src/assets/Tataouine_Images/caption (13).jpg"
import TataouineImage11 from "../src/assets/Tataouine_Images/caption.jpg"
import NabeulImages1 from "../src/assets/Nabeul_Images/assiette-bon-kif.jpg"
import NabeulImages2 from "../src/assets/Nabeul_Images/byzance-hotel.jpg"
import NabeulImages3 from "../src/assets/Nabeul_Images/c-est-la-fete-au-restaurant.jpg"
import NabeulImages4 from "../src/assets/Nabeul_Images/caption.jpg"
import NabeulImages5 from "../src/assets/Nabeul_Images/chich-khan.jpg"
import NabeulImages6 from "../src/assets/Nabeul_Images/cool-relax.jpg"
import NabeulImages7 from "../src/assets/Nabeul_Images/dar-sabri.jpg"
import NabeulImages8 from "../src/assets/Nabeul_Images/entrance--v2604022.jpg"
import NabeulImages9 from "../src/assets/Nabeul_Images/fb-img-1596472891994.jpg"
import NabeulImages10 from "../src/assets/Nabeul_Images/front-of-pension-les.jpg"
import NabeulImages11 from "../src/assets/Nabeul_Images/hotel-club-riadh.jpg"
import NabeulImages12 from "../src/assets/Nabeul_Images/hotel-les-colombes.jpg"
import NabeulImages13 from "../src/assets/Nabeul_Images/kasbah-of-hammamet.jpg"
import NabeulImages14 from "../src/assets/Nabeul_Images/kerkouane.jpg"
import NabeulImages15 from "../src/assets/Nabeul_Images/l-entree.jpg"
import NabeulImages17 from "../src/assets/Nabeul_Images/photo0jpg (1).jpg"
import NabeulImages18 from "../src/assets/Nabeul_Images/photo0jpg.jpg"
import NabeulImages19 from "../src/assets/Nabeul_Images/photo3jpg.jpg"
import NabeulImages20 from "../src/assets/Nabeul_Images/piscine.jpg"
import NabeulImages21 from "../src/assets/Nabeul_Images/suite-ulysse.jpg"
import NabeulImages22 from "../src/assets/Nabeul_Images/vue-piscine-et-mer.jpg"
import NabeulImages23 from "../src/assets/Nabeul_Images/yasmin-hammamet.jpg"
import MahdiaImage2 from "../src/assets/Mahdia_Images/20171004-111120-largejpg.jpg"
import MahdiaImage3 from "../src/assets/Mahdia_Images/el-mouradi-cap-mahdia.jpg"
import MahdiaImage5 from "../src/assets/Mahdia_Images/el-mouradi-mahdia.jpg"
import MahdiaImage6 from "../src/assets/Mahdia_Images/emplacement-sidi-salem.jpg"
import MahdiaImage7 from "../src/assets/Mahdia_Images/gourmandise-mahdia.jpg"
import MahdiaImage8 from "../src/assets/Mahdia_Images/gusto-del-mar.jpg"
import MahdiaImage9 from "../src/assets/Mahdia_Images/hotel-mahdia-summer-vibes.jpg"
import MahdiaImage10 from "../src/assets/Mahdia_Images/iberostar-selection-royal.jpg"
import MahdiaImage11 from "../src/assets/Mahdia_Images/img-20181001-111943-largejpg.jpg"
import MahdiaImage12 from "../src/assets/Mahdia_Images/les-trois-desert-et-les.jpg"
import MahdiaImage14 from "../src/assets/Mahdia_Images/mahdia-beach-aquapark.jpg"
import MahdiaImage15 from "../src/assets/Mahdia_Images/mahdia-palace-thalasso.jpg"
import MahdiaImage17 from "../src/assets/Mahdia_Images/main-pool--v5693854.jpg"
import MahdiaImage19 from "../src/assets/Mahdia_Images/outdoor-pool--v5694587.jpg"
import MahdiaImage21 from "../src/assets/Mahdia_Images/outdoor-pool--v7245939.jpg"
import MahdiaImage22 from "../src/assets/Mahdia_Images/outdoor-pool--v7246325.jpg"
import MahdiaImage23 from "../src/assets/Mahdia_Images/outdoor-pool--v7303006.jpg"
import MahdiaImage25 from "../src/assets/Mahdia_Images/outdoor-pool--v7303331.jpg"
import MahdiaImage26 from "../src/assets/Mahdia_Images/photo0jpg.jpg"
import MahdiaImage27 from "../src/assets/Mahdia_Images/photo2jpg.jpg"
import MahdiaImage28 from "../src/assets/Mahdia_Images/poisson-de-jour.jpg"
import MahdiaImage29 from "../src/assets/Mahdia_Images/restaurant-pizzeria-da.jpg"
import MahdiaImage30 from "../src/assets/Mahdia_Images/salon-de-the.jpg"
import TunisImage1 from "../src/assets/Tunis_Images/appartement-de-50m2-entieremen.jpg"
import TunisImage2 from "../src/assets/Tunis_Images/au-coeur-de-la-medina.jpg"
import TunisImage3 from "../src/assets/Tunis_Images/caption (1).jpg"
import TunisImage4 from "../src/assets/Tunis_Images/caption (2).jpg"
import TunisImage5 from "../src/assets/Tunis_Images/caption.jpg"
import TunisImage7 from "../src/assets/Tunis_Images/chambre-double.jpg"
import TunisImage8 from "../src/assets/Tunis_Images/el-ali.jpg"
import TunisImage9 from "../src/assets/Tunis_Images/el-dar-restaurant.jpg"
import TunisImage10 from "../src/assets/Tunis_Images/exterior-view (1).jpg"
import TunisImage11 from "../src/assets/Tunis_Images/exterior-view (2).jpg"
import TunisImage12 from "../src/assets/Tunis_Images/exterior-view.jpg"
import TunisImage13 from "../src/assets/Tunis_Images/hotel-belvedere-fourati.jpg"
import TunisImage14 from "../src/assets/Tunis_Images/hotel-le-consul.jpg"
import TunisImage15 from "../src/assets/Tunis_Images/hotel-royal-victoria.jpg"
import TunisImage16 from "../src/assets/Tunis_Images/img.jpg"
import TunisImage17 from "../src/assets/Tunis_Images/king-city-view-deluxe.jpg"
import TunisImage18 from "../src/assets/Tunis_Images/la-closerie.jpg"
import TunisImage19 from "../src/assets/Tunis_Images/laico-tunis.jpg"
import TunisImage20 from "../src/assets/Tunis_Images/movenpick-hotel-du-lac.jpg"
import TunisImage21 from "../src/assets/Tunis_Images/museo-del-bardo.jpg"
import TunisImage22 from "../src/assets/Tunis_Images/nejma-room--v12008326.jpg"
import TunisImage23 from "../src/assets/Tunis_Images/the-carlton-loby-art.jpg"
import TunisImage24 from "../src/assets/Tunis_Images/theater.jpg"
import TunisImage25 from "../src/assets/Tunis_Images/tunis-bab-bahr.jpg"
import TunisImage26 from "../src/assets/Tunis_Images/vue-de-l-exterieure.jpg"
let TataouineImages = [
    TataouineImage1,TataouineImage2,TataouineImage3,TataouineImage4,TataouineImage5,TataouineImage6,TataouineImage7,TataouineImage8,TataouineImage9,TataouineImage10,TataouineImage11
]
let NabeulImages = [
    NabeulImages1,NabeulImages2,NabeulImages3,NabeulImages4,NabeulImages5,NabeulImages6,NabeulImages7,NabeulImages8,NabeulImages9,NabeulImages10,NabeulImages11,NabeulImages12,NabeulImages13,NabeulImages14,NabeulImages15,NabeulImages17,NabeulImages18,NabeulImages19,NabeulImages20,NabeulImages21,NabeulImages22,NabeulImages23
];
let MahdiaImages = [
    MahdiaImage2,MahdiaImage3,MahdiaImage5,MahdiaImage6,MahdiaImage7,MahdiaImage8,MahdiaImage9,MahdiaImage10,MahdiaImage11,MahdiaImage12,MahdiaImage14,MahdiaImage15,MahdiaImage17,MahdiaImage19,MahdiaImage21,MahdiaImage22,MahdiaImage23,MahdiaImage25,MahdiaImage26,MahdiaImage27,MahdiaImage28,MahdiaImage29,MahdiaImage30
];
let TunisImages = [
    TunisImage1,TunisImage2,TunisImage3,TunisImage4,TunisImage5,TunisImage7,TunisImage8,TunisImage9,TunisImage10,TunisImage11,TunisImage12,TunisImage13,TunisImage14,TunisImage15,TunisImage16,TunisImage17,TunisImage18,TunisImage19,TunisImage20,TunisImage21,TunisImage22,TunisImage23,TunisImage24,TunisImage25,TunisImage26,
]
export {TataouineImages,NabeulImages,MahdiaImages,TunisImages}